name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Initialise
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run the PytTest script
        run: python -m pytest 
